### PR TITLE
Change number of PSU in INDEX_POWER_LIMIT_CONFIG to fix PE00JCDG

### PR DESCRIPTION
**Pull request by ruby452**
For attribute INDEX_POWER_LIMIT_CONFIG reduce the total number of PSUs from 2 to 1 and from 4 to 1.

### CODE REVIEW

**Review by baileysh — CHANGES_REQUESTED** [review]
This is not correct.   INDEX_POWER_LIMIT_CONFIG is not 24 entries.
2U	<default>0x51E90202,0x51E90102,0x51E90201,0x51E90101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</default>

4U
<default>0x2B1D0202,0x2B1D0102,0x2B1D0204,0x2B1D0104,0x2B1E0202,0x2B1E0204,0x2B1D0201,0x2B1D0101,0x2B1D0203,0x2B1D0103,0x2B1E0201,0x2B1E0203,0,0,0,0,0,0,0,0,0,0,0,0</default>

and Watts  added to INDEX_N_PLUS_ONE_BULK_POWER_LIMIT_WATTS and INDEX_N_BULK_POWER_LIMIT_WATTS

**Comment by nschwart** [comment]
I'm confused.  It looks like the 2 and 4 power supply options were removed and replaced with the 1 and 3 power supply options.  The 1 and 3 PSU options should have been added, the 2 and 4 still need to be there.

**Comment by baileysh** [comment]
2U:
	<attribute>
		<id>INDEX_N_BULK_POWER_LIMIT_WATTS</id>
		<default>1880,930,1880,930,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</default>
	</attribute>
	<attribute>
		<id>INDEX_N_PLUS_ONE_BULK_POWER_LIMIT_WATTS</id>
		<default>2500,1250,2500,1250,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</default>
	</attribute>
	<attribute>
		<id>INDEX_POWER_LIMIT_CONFIG</id>
		<default>0x51E90202,0x51E90102,0x51E90201,0x51E90101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</default>
	</attribute>

**Comment by baileysh** [comment]
4U:
	<attribute>
		<id>INDEX_N_BULK_POWER_LIMIT_WATTS</id>
		<default>1120,930,2260,1880,1500,3020,1120,930,2260,1880,1500,3020,0,0,0,0,0,0,0,0,0,0,0,0</default>
	</attribute>
	<attribute>
		<id>INDEX_N_PLUS_ONE_BULK_POWER_LIMIT_WATTS</id>
		<default>1500,1250,3000,2500,2000,4000,1500,1250,3000,2500,2000,4000,0,0,0,0,0,0,0,0,0,0,0,0</default>
	</attribute>
	<attribute>
		<id>INDEX_POWER_LIMIT_CONFIG</id>
		<default>0x2B1D0202,0x2B1D0102,0x2B1D0204,0x2B1D0104,0x2B1E0202,0x2B1E0204,0x2B1D0201,0x2B1D0101,0x2B1D0203,0x2B1D0103,0x2B1E0201,0x2B1E0203,0,0,0,0,0,0,0,0,0,0,0,0</default>
	</attribute>

**Review by baileysh — CHANGES_REQUESTED** [review]
INDEX_POWER_LIMIT_CONFIG
item 12 is 0x2B1E0204 and wrong,,, did not check the upper N N+1 watts.

**Review by baileysh — APPROVED** [review]
That looks good.

**Review by nschwart — COMMENTED** [review]
Looks good to me.  Thanks!

**Pull request merged**
